name: Build Melodic

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@0.10.0'
        env: {ROS_DISTRO: melodic, ROS_REPO: testing}
